name: SurvivalGames
version: '${project.version}'
main: hwnet.survivalgames.SG
api-version: 1.18
authors: [ Nedlow ]
description: Dedicated Survival Games game mode, written for hwNET.
depend:
  - WorldEdit
commands:
  sg:
  addspawn:
    permission: sg.admin
  addarena:
    permission: sg.admin
  vote:
  editarena:
    permission: sg.admin
  savearena:
    permission: sg.admin
  spawn:
    aliases: lobby
  fstart:
    permission: sg.admin
  forcedm:
    permission: sg.admin
  addtime:
    permission: sg.admin
  join:
  leave:
  setlobby:
    permission: sg.admin
  tploc:
    permission: sg.admin
  points:
  volunteer:
  spectate:
  devmode:
    permission: sg.admin
    description: Toggles developer mode, only staff can access
  softstop:
    permission: sg.admin
  resourcepack:
  setsign:
    permission: sg.admin
  editsign:
    permission: sg.admin
    description: Open the sign menu to edit.
  cancel:
    permission: sg.admin
    usage: /cancel [time in seconds]
    description: Cancels the current game.
